{"uuid": "39eb3ccc-22a6-4232-b1d5-02d2e730c98a", "children": ["0d87ba57-3261-4320-bd69-79f3289b1f9f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "ValueError: no option named '--device-udid'\n", "trace": "  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/admin/PycharmProjects/pythonProject/tests/conftest.py\", line 11, in driver\n    device_udid = request.config.getoption(\"--device-udid\")\n  File \"/Users/admin/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 1705, in getoption\n    raise ValueError(f\"no option named {name!r}\") from e\n"}, "start": 1746526274345, "stop": 1746526274345}], "start": 1746526274345, "stop": 1746526274486}